import { UploadVideoService } from './upload-video-service';
import { ExtractAudioService } from './extract-audio-service';
import { TranscribeAudioService } from './transcribe-audio-service';
import { WorkflowCleanupService } from './workflow-cleanup';
import { AgentStateStore } from './agent-state-store';
import { JobStateStore } from './job-state-store';
import { ReferenceService } from './reference-service';
import { AudioExtractorService } from './audio-extractor';
import { GPTEnhancementService } from './gpt-enhancement-service';
import { AzureClientService } from './azure-client';
import { HealthCheckService } from './health-check-service';
import { SummarizeContentService } from './summarize-content-service';
import { ExtractKeyPointsService } from './extract-key-points-service';
import { AnalyzeSentimentService } from './analyze-sentiment-service';
import { IdentifyTopicsService } from './identify-topics-service';
import { WhisperService } from './whisper-service';
export declare class ServiceManager {
    private static instance;
    private uploadVideoService?;
    private extractAudioService?;
    private transcribeAudioService?;
    private workflowCleanupService?;
    private agentStateStore?;
    private jobStateStore?;
    private referenceService?;
    private audioExtractorService?;
    private gptEnhancementService?;
    private azureClientService?;
    private healthCheckService?;
    private summarizeContentService?;
    private extractKeyPointsService?;
    private analyzeSentimentService?;
    private identifyTopicsService?;
    private whisperService?;
    private constructor();
    static getInstance(): ServiceManager;
    getUploadVideoService(): UploadVideoService;
    getExtractAudioService(): ExtractAudioService;
    getTranscribeAudioService(): TranscribeAudioService;
    getWorkflowCleanupService(): WorkflowCleanupService;
    getAgentStateStore(): AgentStateStore;
    getJobStateStore(): JobStateStore;
    getReferenceService(): ReferenceService;
    getAudioExtractorService(): AudioExtractorService;
    getGPTEnhancementService(): GPTEnhancementService;
    getAzureClientService(): AzureClientService;
    getHealthCheckService(): HealthCheckService;
    getSummarizeContentService(): SummarizeContentService;
    getExtractKeyPointsService(): ExtractKeyPointsService;
    getAnalyzeSentimentService(): AnalyzeSentimentService;
    getIdentifyTopicsService(): IdentifyTopicsService;
    getWhisperService(): WhisperService;
    static dispose(): void;
    getLoadedServices(): string[];
}
//# sourceMappingURL=service-manager.d.ts.map